---
# Root User password R00t
apiVersion: v1
data:
  password: UjAwdA==
kind: Secret
metadata:
  name: mysql-root-pass
  namespace: default
type: Opaque

---
# External User name = callicoder  password =c@ll1c0d3r
apiVersion: v1
data:
  password: Y0BsbDFjMGQzcg==
  username: Y2FsbGljb2Rlcg==
kind: Secret
metadata:
  
  name: mysql-user-pass
  namespace: default
  
type: Opaque

---
# A User will automatically create Database =polls and its url will be jdbc:mysql://polling-app-mysql:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
# My sql listens on port 3306
# polling-app-mysql would be service name which we would be creating
apiVersion: v1
data:
  database: cG9sbHM=
  url: amRiYzpteXNxbDovL3BvbGxpbmctYXBwLW15c3FsOjMzMDYvcG9sbHM/dXNlU1NMPWZhbHNlJnNlcnZlclRpbWV6b25lPVVUQyZ1c2VMZWdhY3lEYXRldGltZUNvZGU9ZmFsc2U=
kind: Secret
metadata:
  
  name: mysql-db-url
  namespace: default
  
type: Opaque
