apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
    

---
apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: devops
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jira
    
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops
spec:
  selector: 
    app: nexus-server
  type: NodePort  
  ports:
    - port: 8081
      targetPort: 8081
      